# 常规配置
appname: excel_tool
httpport: 8090
runmode: dev
autorender: false
copyrequestbody: true
EnableDocs: true
sqlconn:
sessionon: true

#mysql配置
mysql:
  type: mysql
  user: root
  password: q*egyiKm%4dx
  host: 47.119.168.227
  port: 3306
  dbName: blog